name: Unit Tests

on:
  push:
    branches-ignore: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vite-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: npm install
        run: npm install

      - name: Build site
        env:
          CI: false
        run: npm run build

      - name: Run tests
        run: npm run test
