name: Unit Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: fe install
        run: cd fe && yarn install

      - name: fe test
        run: |
          cd fe
          yarn build
          yarn test

    # - name: be install
    #   run: cd be && npm install
